export enum ArticleType {
  IT = "IT",
  BUSINESS = "BUSINESS",
  HEALTH = "HEALTH",
  SCIENCE = "SCIENCE",
  EDUCATION = "EDUCATION",
  SPORTS = "SPORTS",
  ENTERTAINMENT = "ENTERTAINMENT",
  POLITICS = "POLITICS",
  TRAVEL = "TRAVEL",
  LIFESTYLE = "LIFESTYLE",
}
