export enum ArticleType {
  ALL = "all",
  IT = "it",
  BUSINESS = "business",
  HEALTH = "health",
  SCIENCE = "science",
  EDUCATION = "education",
  SPORTS = "sports",
  ENTERTAINMENT = "entertainment",
  POLITICS = "politics",
  TRAVEL = "travel",
  LIFESTYLE = "lifestyle",
  TECH = "tech",
  ECOLOGY = "ecology",
  FASHION = "fashion",
  URBAN = "urban",
  MEDIA = "media",
  CULTURE = "culture",
  DESIGN = "design",
}
