name: linting, testing, building
on:
  push:
    branches: [master, main, dev]
  pull_request:
    branches: [master, main, dev]
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build-and-ui-testing:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm ci --force
      - name: Build production project
        run: npm run build:prod
        if: always()
      - name: Build storybook
        run: npm run storybook:build
        if: always()

      - name: Screenshot testing
        run: npm run test:ui:ci
        continue-on-error: true

      - name: Unit testing
        if: always()
        run: npm run test:unit

      - name: Generate HTML report
        run: npm run test:ui:report
        if: always()

      - name: Move loki to reports folder
        run: mv .loki reports/

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload HTML reports to GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          path: "reports"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
#   checks:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [17.x]
#     steps:
#       - uses: actions/checkout@v2
#       - name: Staring Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: install modules
#         run: npm ci --force
#       - name: linting typescript
#         run: npm run lint:ts
#         if: always()
#       - name: linting css
#         run: npm run lint:scss
